name: check pull_request branch name
on:
  # Only 'pull_request' event is supported for this action
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  prcheck-job:
    runs-on: ubuntu-latest
    name: check PR branch name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Check branch name action step
      - name: check PR branch name
        uses: mana544/check-pr-ref-name@v1

