name: PR Branch check
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  job1:
    name: JOB 1
    runs-on: ubuntu-latest
    env:
      # プルリクエストイベントactionキーの値(string)
      # 以下のURLの説明のどれかが入る
      # 'synchronize' とか
      # https://docs.github.com/ja/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
      PR_2: ${{ github.event.action }}

      # イベント名
      # このワークフローはpull_requestイベントトリガーなので
      # 'pull_request' がはいる
      PR_3: ${{ github.event_name }}

      # PR番号
      # 正の整数ではいる
      PR_4: ${{ github.event.number }}

      # イベントトリガーした人のログイン名
      PR_5: ${{ github.event.sender.login }}

      # イベントトリガーした人のURL
      PR_6: ${{ github.event.sender.html_url }}

      # senderオブジェクト
      PR_7: ${{ toJSON(github.event.sender) }}

      # PR URL
      PR_8: ${{ github.event.pull_request.html_url }}

      # base ref
      PR_9: ${{ github.event.pull_request.base.ref }}

    steps:
      - uses: actions/checkout@v2
      - name: Check branch
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./.github/workflows/pr_branch_check.js')
            script({github, context})

